---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mavenwebappdeployment
 namespace: karthi
spec:
 replicas: 2
 selector: 
   matchLabels: 
     app: mavenwebapp
 template:
  metadata:
   name: mavenwebapppod
   labels:
     app: mavenwebapp	 
  spec: 
    containers:
    - name: mavenwebappcontainer
      image: karthikeyangitt/tomcatimage:{{BUILD_NUMBER}}
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: mavenwebappsvc
 namespace: karthi
spec:
  selector:
   app: mavenwebapp
  ports:
   - port: 80
     targetPort: 8080
...


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource1
  namespace: karthi
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:  # Indentation fixed here
        paths:
        - path: /karthikeyan
          pathType: Prefix
          backend:
            service:
              name: mavenwebappsvc
              port:
                number: 80

